var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var tupleNumStr;
myString = 'Hello Universe';
myNum = 20;
myBool = true;
myVar = 5.55;
strArr = ['Hello', 'Type'];
numArr = [0, 1, 2, 3];
tupleNumStr = ['Hi', 2];
myString = myString.slice(6, myString.length);
console.log(myString);
document.body.innerHTML = myString;
